# Generated by Django 4.2.8 on 2024-01-12 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.PositiveIntegerField()),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=7)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('period_requested', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(36), django.core.validators.MaxValueValidator(84)])),
                ('period_approved', models.SmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(36), django.core.validators.MaxValueValidator(84)])),
                ('sign', models.SmallIntegerField(default=4307)),
                ('contract', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('LOAN_CREATED', 'LOAN_CREATED'), ('DECLINED', 'DECLINED'), ('EXPIRED', 'EXPIRED')], default='NEW', max_length=32)),
            ],
        ),
    ]
