# Generated by Django 4.2.8 on 2024-01-13 11:14

from decimal import Decimal
from django.db import migrations, models
import orders.utils


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_amount_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_requested',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000000'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='sign',
            field=models.SmallIntegerField(default=orders.utils.create_sign),
        ),
    ]
